# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dlserver.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf import example_pb2 as example__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dlserver.proto',
  package='dlserver',
  syntax='proto3',
  serialized_options=_b('\n\025dlserver.grpc.exampleB\007DLProtoP\001\242\002\003RTG'),
  serialized_pb=_b('\n\x0e\x64lserver.proto\x12\x08\x64lserver\x1a\rexample.proto\"2\n\x0b\x45xampleList\x12#\n\x08\x65xamples\x18\x01 \x03(\x0b\x32\x11.dlserver.Example\"I\n\tDLRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12+\n\x0c\x65xample_list\x18\x02 \x01(\x0b\x32\x15.dlserver.ExampleList2J\n\x10\x45xamplesDLServer\x12\x36\n\nGetOutputs\x12\x13.dlserver.DLRequest\x1a\x11.dlserver.Example\"\x00\x42(\n\x15\x64lserver.grpc.exampleB\x07\x44LProtoP\x01\xa2\x02\x03RTGb\x06proto3')
  ,
  dependencies=[example__pb2.DESCRIPTOR,])




_EXAMPLELIST = _descriptor.Descriptor(
  name='ExampleList',
  full_name='dlserver.ExampleList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='examples', full_name='dlserver.ExampleList.examples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=93,
)


_DLREQUEST = _descriptor.Descriptor(
  name='DLRequest',
  full_name='dlserver.DLRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='dlserver.DLRequest.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='example_list', full_name='dlserver.DLRequest.example_list', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=168,
)

_EXAMPLELIST.fields_by_name['examples'].message_type = example__pb2._EXAMPLE
_DLREQUEST.fields_by_name['example_list'].message_type = _EXAMPLELIST
DESCRIPTOR.message_types_by_name['ExampleList'] = _EXAMPLELIST
DESCRIPTOR.message_types_by_name['DLRequest'] = _DLREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExampleList = _reflection.GeneratedProtocolMessageType('ExampleList', (_message.Message,), dict(
  DESCRIPTOR = _EXAMPLELIST,
  __module__ = 'dlserver_pb2'
  # @@protoc_insertion_point(class_scope:dlserver.ExampleList)
  ))
_sym_db.RegisterMessage(ExampleList)

DLRequest = _reflection.GeneratedProtocolMessageType('DLRequest', (_message.Message,), dict(
  DESCRIPTOR = _DLREQUEST,
  __module__ = 'dlserver_pb2'
  # @@protoc_insertion_point(class_scope:dlserver.DLRequest)
  ))
_sym_db.RegisterMessage(DLRequest)


DESCRIPTOR._options = None

_EXAMPLESDLSERVER = _descriptor.ServiceDescriptor(
  name='ExamplesDLServer',
  full_name='dlserver.ExamplesDLServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=170,
  serialized_end=244,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOutputs',
    full_name='dlserver.ExamplesDLServer.GetOutputs',
    index=0,
    containing_service=None,
    input_type=_DLREQUEST,
    output_type=example__pb2._EXAMPLE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXAMPLESDLSERVER)

DESCRIPTOR.services_by_name['ExamplesDLServer'] = _EXAMPLESDLSERVER

# @@protoc_insertion_point(module_scope)
